USE cs6400_sp25_team001;
INSERT INTO Breed (breed_type) VALUES
('Affenpinscher'), ('Afghan Hound'), ('Airedale Terrier'), ('Akbash Dog'), ('Akita'),
('Alapaha Blue Blood Bulldog'), ('Alaskan Husky'), ('Alaskan Malamute'), ('American Bulldog'), ('American Eskimo'),
('American Foxhound'), ('American Pit Bull Terrier'), ('American Staffordshire Terrier'), ('American Water Spaniel'),
('Anatolian Shepherd Dog'), ('Aussiedoodle'), ('Australian Cattle Dog'), ('Australian Kelpie'), ('Australian Shepherd'),
('Australian Terrier'), ('Azawakh'), ('Basador'), ('Basenji'), ('Basset Bleu de Gascogne'), ('Basset Hound'),
('Beagle'), ('Bearded Collie'), ('Beauceron'), ('Bedlington Terrier'), ('Belgian Laekenois'), ('Belgian Malinois'),
('Belgian Sheepdog'), ('Belgian Tervuren'), ('Bergamasco'), ('Berger Picard'), ('Bernese Mountain Dog'),
('Bichon Frise'), ('Black and Tan Coonhound'), ('Black Russian Terrier'), ('Bloodhound'), ('Blue Picardy Spaniel'),
('Bluetick Coonhound'), ('Boerboel'), ('Bolognese'), ('Border Collie'), ('Border Terrier'), ('Borzoi'),
('Boston Terrier'), ('Bouvier des Flandres'), ('Boxer'), ('Boykin Spaniel'), ('Bracco Italiano'), ('Briard'),
('Brussels Griffon'), ('Bull Terrier'), ('Bulldog'), ('Bullmastiff'), ('Cairn Terrier'), ('Canaan Dog'),
('Cane Corso'), ('Cardigan Welsh Corgi'), ('Catahoula Leopard Dog'), ('Caucasian Ovcharka'), ('Cavalier King Charles Spaniel'),
('Cavapom'), ('Cavapoo'), ('Cesky Terrier'), ('Chesapeake Bay Retriever'), ('Chihuahua'), ('Chinese Crested'),
('Chinese Shar-Pei'), ('Chinook'), ('Chow Chow'), ('Chug'), ('Cirneco dell''Etna'), ('Clumber Spaniel'),
('Cockapoo'), ('Cocker Spaniel'), ('Collie'), ('Coton de Tulear'), ('Curly-Coated Retriever'), ('Dachshund'),
('Dalmatian'), ('Dandie Dinmont Terrier'), ('Doberman Pinscher'), ('Dogo Argentino'), ('Dogue de Bordeaux'),
('Doxiepoo'), ('English Cocker Spaniel'), ('English Foxhound'), ('English Setter'), ('English Springer Spaniel'),
('English Toy Spaniel'), ('Entlebucher Mountain Dog'), ('Eurasier'), ('Field Spaniel'), ('Fila Brasileiro'),
('Finnish Lapphund'), ('Finnish Spitz'), ('Flat-Coated Retriever'), ('Fox Terrier'), ('French Bulldog'),
('German Pinscher'), ('German Shepherd Dog'), ('German Shorthaired Pointer'), ('German Spitz'), ('German Wirehaired Pointer'),
('Giant Schnauzer'), ('Glen of Imaal Terrier'), ('Golden Retriever'), ('Goldendoodle'), ('Gordon Setter'),
('Great Dane'), ('Great Pyrenees'), ('Greater Swiss Mountain Dog'), ('Greyhound'), ('Groenendael'), ('Havanese'),
('Harrier'), ('Havapoo'), ('Ibizan Hound'), ('Icelandic Sheepdog'), ('Irish Red and White Setter'), ('Irish Setter'),
('Irish Terrier'), ('Irish Water Spaniel'), ('Irish Wolfhound'), ('Italian Greyhound'), ('Jack Russell Terrier'),
('Japanese Chin'), ('Keeshond'), ('Kerry Blue Terrier'), ('Komondor'), ('Kooikerhondje'), ('Kromfohrlander'),
('Kuvasz'), ('Labradoodle'), ('Labrador Retriever'), ('Lagotto Romagnolo'), ('Lakeland Terrier'), ('Lhasa Apso'),
('Lhasapoo'), ('Leonberger'), ('Longdog'), ('Lowchen'), ('Lurcher'), ('Maltese'), ('Maltipoo'), ('Manchester Terrier'),
('Mastiff'), ('Miniature American Shepherd'), ('Miniature Bull Terrier'), ('Miniature Pinscher'),
('Miniature Schnauzer'), ('Mixed'), ('Mudi'), ('Neapolitan Mastiff'), ('Newfoundland'), ('Norfolk Terrier'),
('Norwegian Buhund'), ('Norwegian Elkhound'), ('Norwegian Lundehund'), ('Norwich Terrier'), ('Nova Scotia Duck Tolling Retriever'),
('Old English Sheepdog'), ('Otterhound'), ('Papillon'), ('Pekeapoo'), ('Pekingese'), ('Pembroke Welsh Corgi'),
('Perro de Presa Canario'), ('Peruvian Inca Orchid'), ('Petit Basset Griffon Vendeen'), ('Pharaoh Hound'),
('Plott'), ('Pointer'), ('Polish Lowland Sheepdog'), ('Pomapoo'), ('Pomeranian'), ('Pomsky'), ('Poodle'),
('Pug'), ('Pugapoo'), ('Puli'), ('Pumi'), ('Rat Terrier'), ('Redbone Coonhound'), ('Rhodesian Ridgeback'),
('Rottweiler'), ('Russian Toy'), ('Saint Bernard'), ('Saluki'), ('Samoyed'), ('Schapendoes'), ('Schipperke'),
('Schnoodle'), ('Scottish Deerhound'), ('Scottish Terrier'), ('Sealyham Terrier'), ('Shetland Sheepdog'),
('Shiba Inu'), ('Shih Tzu'), ('Shihpoo'), ('Siberian Husky'), ('Silken Windhound'), ('Silky Terrier'),
('Skye Terrier'), ('Sloughi'), ('Small Munsterlander Pointer'), ('Soft Coated Wheaten Terrier'), ('Spanish Greyhound'),
('Spanish Water Dog'), ('Spinone Italiano'), ('Sprollie'), ('Staffordshire Bull Terrier'), ('Standard Schnauzer'),
('Sussex Spaniel'), ('Swedish Lapphund'), ('Swedish Vallhund'), ('Thai Ridgeback'), ('Tibetan Mastiff'),
('Tibetan Spaniel'), ('Tibetan Terrier'), ('Toy Fox Terrier'), ('Toy Poodle'), ('Treeing Walker Coonhound'),
('Tosa Ken'), ('Vizsla'), ('Volpino Italiano'), ('Weimaraner'), ('Welsh Springer Spaniel'), ('Welsh Terrier'),
('West Highland White Terrier'), ('Whippet'), ('Wirehaired Pointing Griffon'), ('Wirehaired Vizsla'), ('Xoloitzcuintli'),
('Yorkipoo'), ('Yorkshire Terrier'), ('Unknown');

INSERT INTO ExpenseCategory (category_name) VALUES
('Veterinarian fees '), ('Medications'), ('Dental care'), ('Food supplies'),
('Treats and Toys '), ('Leashes, collars, harnesses'), ('Shelter supplies '), ('Grooming supplies'),
('Transportation'), ('Miscellaneous');

INSERT INTO MicrochipVendor (vendor_name) VALUES
('AKC Reunite'), ('AVID'), ('Banfield TruPaws'), ('BarkCode Solutions'),
('CritterID Systems'), ('Datamars'), ('Destron Fearing'), ('FurSecure ID'),
('FurTrack Microchips'), ('FurryTag Systems'), ('HomeAgain'), ('LifeChip'),
('PawID Technologies'), ('PawPrint ID'), ('PawTech Microchips'),
('PetGuardian Chips'), ('PetLink'), ('PetSafe Chips'), ('Trovan'), ('24PetWatch');